"""Add genres table

Revision ID: 51cfb99c2727
Revises: c7923747178b
Create Date: 2026-09-10 10:59:48.223351

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '51cfb99c2727'
down_revision: Union[str, Sequence[str], None] = 'c7923747178b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres'))
    )
    op.add_column('movies', sa.Column('genre_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('movies') as batch_op:
        batch_op.create_foreign_key(op.f('fk_movies_genre_id_genres'), 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies') as batch_op:
        batch_op.drop_constraint(op.f('fk_movies_genre_id_genres'), type_='foreignkey')
        batch_op.drop_column('genre_id')
    op.drop_table('genres')
    # ### end Alembic commands ###
