"""Add indexes to movie and unique for genre

Revision ID: b8ffc12017a7
Revises: 51cfb99c2727
Create Date: 2026-09-10 12:06:17.698339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ffc12017a7'
down_revision: Union[str, Sequence[str], None] = '51cfb99c2727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_genres_name'), 'genres', ['name'])
    op.create_index(op.f('ix_movies_genre_id'), 'movies', ['genre_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_genre_id'), table_name='movies')
    op.drop_constraint(op.f('uq_genres_name'), 'genres', type_='unique')
    # ### end Alembic commands ###
