"""Make release year non nullable

Revision ID: dc030a9a6bac
Revises: e005ac9f0ab2
Create Date: 2026-09-09 21:51:07.661146

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dc030a9a6bac'
down_revision: Union[str, Sequence[str], None] = 'e005ac9f0ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE movies SET release_year = 1900 WHERE release_year IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
