"""Add release year to movies

Revision ID: e005ac9f0ab2
Revises: 423b8ac8c58d
Create Date: 2026-09-09 21:47:32.200343

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e005ac9f0ab2'
down_revision: Union[str, Sequence[str], None] = '423b8ac8c58d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'release_year')
    # ### end Alembic commands ###
